// @vitest-environment node
import { describe, expect, it } from "vitest";
import { WATERMARK_LABEL } from "../src/entitlements";
import { buildShortlistHtml } from "../src/exportShortlist";
import { defaultPreferenceProfile } from "../src/workspace/constants";

describe("buildShortlistHtml watermark branch", () => {
  it("stamps the Free watermark into the footer and a per-page corner", () => {
    const html = buildShortlistHtml([], {}, defaultPreferenceProfile, [], {
      watermark: true
    });
    // Corner element repeats on each printed page.
    expect(html).toContain('class="watermark-corner"');
    expect(html).toContain(WATERMARK_LABEL);
    // The exact label copy the paywall promises.
    expect(html).toContain("Generated with UniMap Condor Free");
  });

  it("defaults to watermarked when no options are passed (safe Free default)", () => {
    const html = buildShortlistHtml([], {}, defaultPreferenceProfile, []);
    expect(html).toContain('class="watermark-corner"');
    expect(html).toContain(WATERMARK_LABEL);
  });

  it("omits the watermark entirely for Pro exports", () => {
    const html = buildShortlistHtml([], {}, defaultPreferenceProfile, [], {
      watermark: false
    });
    // The corner element is not emitted, and the label text appears nowhere
    // (the static `.watermark-corner` CSS rule carries no label text).
    expect(html).not.toContain('<div class="watermark-corner">');
    expect(html).not.toContain(WATERMARK_LABEL);
    // The rest of the document still renders.
    expect(html).toContain("Generated by UniMap Condor.");
  });
});
