import type { AdvisorCard } from "./types";

const polytechniqueAliases = [
  "Polytechnique Montréal",
  "Polytechnique Montreal",
  "École Polytechnique de Montréal",
  "Ecole Polytechnique de Montreal",
  "Polytechnic School of Montreal"
];

const udemAliases = [
  "Université de Montréal",
  "University of Montreal",
  "University of Montréal",
  "UdeM",
  "Montreal University"
];

const ucDavisAliases = [
  "University of California, Davis",
  "University of California Davis",
  "University of California-Davis",
  "UC Davis",
  "UCD"
];

const mcmasterAliases = [
  "McMaster University",
  "McMaster",
  "Mac",
  "McMaster Engineering"
];

const uclaAliases = [
  "University of California, Los Angeles",
  "University of California Los Angeles",
  "UCLA",
  "UC Los Angeles",
  "UCLA Samueli"
];

const uscAliases = [
  "University of Southern California",
  "USC",
  "Southern California",
  "USC Viterbi"
];

export const localAdvisorCards: AdvisorCard[] = [
  {
    id: "foutse-khomh",
    fullName: "Foutse Khomh",
    institutionName: "Polytechnique Montréal",
    institutionAliases: polytechniqueAliases,
    department: "Software Engineering / Mila",
    priority: "S",
    priorityScore: 98,
    fitSummary: "Software quality, ML/AI systems reliability, LLM code generation benchmarks, and multi-agent evaluation.",
    contactAngle: "LLM code generation QA/testing, robustness of AI software systems.",
    researchAreas: ["Software quality", "AI reliability", "LLM code generation", "Multi-agent evaluation"],
    targetPrograms: ["Software Engineering", "Computer Engineering", "Mila-affiliated research"],
    outreachStatus: "External safer outreach",
    sourceLabel: "Vault advisor scan, 2026-05-25"
  },
  {
    id: "heng-li",
    fullName: "Heng Li",
    institutionName: "Polytechnique Montréal",
    institutionAliases: polytechniqueAliases,
    department: "Software / Systems",
    priority: "S-",
    priorityScore: 94,
    fitSummary: "Software systems performance, reliability, runtime monitoring, and infrastructure quality.",
    contactAngle: "AI software reliability, runtime monitoring, infra quality.",
    researchAreas: ["Software systems", "Performance", "Reliability", "Runtime monitoring"],
    targetPrograms: ["Software Engineering", "Computer Engineering"],
    outreachStatus: "External safer outreach",
    sourceLabel: "Vault advisor scan, 2026-05-25"
  },
  {
    id: "maxime-lamothe",
    fullName: "Maxime Lamothe",
    institutionName: "Polytechnique Montréal",
    institutionAliases: polytechniqueAliases,
    department: "Software Engineering",
    priority: "A+",
    priorityScore: 91,
    fitSummary: "Software engineering, logic programming, computer systems software, and LLM-assisted SE tools.",
    contactAngle: "LLM-assisted software engineering tools, program analysis, testing.",
    researchAreas: ["Software engineering", "Logic programming", "Program analysis", "Testing"],
    targetPrograms: ["Software Engineering"],
    outreachStatus: "External safer outreach",
    sourceLabel: "Vault advisor scan, 2026-05-25"
  },
  {
    id: "mohammad-hamdaqa",
    fullName: "Mohammad Hamdaqa",
    institutionName: "Polytechnique Montréal",
    institutionAliases: polytechniqueAliases,
    department: "Software Engineering",
    priority: "A+",
    priorityScore: 90,
    fitSummary: "Software development, software engineering, systems, and knowledge representation.",
    contactAngle: "Software systems and knowledge representation angle; recruiting signal found.",
    researchAreas: ["Software development", "Systems", "Knowledge representation"],
    targetPrograms: ["Software Engineering"],
    recruitingSignal: "Recruiting signal found",
    outreachStatus: "External safer outreach",
    sourceLabel: "Vault advisor scan, 2026-05-25"
  },
  {
    id: "bentley-oakes",
    fullName: "Bentley Oakes",
    institutionName: "Polytechnique Montréal",
    institutionAliases: polytechniqueAliases,
    department: "Software Engineering",
    priority: "A",
    priorityScore: 86,
    fitSummary: "Software engineering, AI, simulation, and knowledge representation.",
    contactAngle: "AI + simulation + software engineering; recruiting signal found.",
    researchAreas: ["Software engineering", "AI", "Simulation", "Knowledge representation"],
    targetPrograms: ["Software Engineering"],
    recruitingSignal: "Recruiting signal found",
    outreachStatus: "External safer outreach",
    sourceLabel: "Vault advisor scan, 2026-05-25"
  },
  {
    id: "zohreh-sharafi",
    fullName: "Zohreh Sharafi",
    institutionName: "Polytechnique Montréal",
    institutionAliases: polytechniqueAliases,
    department: "Software Engineering",
    priority: "A",
    priorityScore: 84,
    fitSummary: "Software engineering and human factors.",
    contactAngle: "Developer experience, human factors, and software engineering evaluation.",
    researchAreas: ["Software engineering", "Human factors", "Developer experience"],
    targetPrograms: ["Software Engineering"],
    outreachStatus: "External safer outreach",
    sourceLabel: "Vault advisor scan, 2026-05-25"
  },
  {
    id: "ettore-merlo",
    fullName: "Ettore Merlo",
    institutionName: "Polytechnique Montréal",
    institutionAliases: polytechniqueAliases,
    department: "Software / Cybersecurity",
    priority: "A-",
    priorityScore: 80,
    fitSummary: "Cybersecurity, AI, and software engineering.",
    contactAngle: "Security and AI-assisted software engineering overlap.",
    researchAreas: ["Cybersecurity", "AI", "Software engineering"],
    targetPrograms: ["Software Engineering", "Computer Engineering"],
    outreachStatus: "External safer outreach",
    sourceLabel: "Vault advisor scan, 2026-05-25"
  },
  {
    id: "jinghui-cheng",
    fullName: "Jinghui Cheng",
    institutionName: "Polytechnique Montréal",
    institutionAliases: polytechniqueAliases,
    department: "Software Engineering",
    priority: "A-",
    priorityScore: 79,
    fitSummary: "Software engineering, human factors, and information systems design.",
    contactAngle: "Human-centered software systems and information systems design.",
    researchAreas: ["Software engineering", "Human factors", "Information systems"],
    targetPrograms: ["Software Engineering"],
    outreachStatus: "External safer outreach",
    sourceLabel: "Vault advisor scan, 2026-05-25"
  },
  {
    id: "amal-zouaq",
    fullName: "Amal Zouaq",
    institutionName: "Polytechnique Montréal",
    institutionAliases: polytechniqueAliases,
    department: "AI / Knowledge Representation",
    priority: "A-",
    priorityScore: 78,
    fitSummary: "AI and knowledge representation.",
    contactAngle: "Knowledge representation for AI systems; recruiting signal found.",
    researchAreas: ["AI", "Knowledge representation", "Semantic systems"],
    targetPrograms: ["Computer Engineering", "AI-related research"],
    recruitingSignal: "Recruiting signal found",
    outreachStatus: "External safer outreach",
    sourceLabel: "Vault advisor scan, 2026-05-25"
  },
  {
    id: "omar-abdul-wahab",
    fullName: "Omar Abdul Wahab",
    institutionName: "Polytechnique Montréal",
    institutionAliases: polytechniqueAliases,
    department: "AI / Cybersecurity",
    priority: "B+",
    priorityScore: 73,
    fitSummary: "AI and cybersecurity overlap.",
    contactAngle: "AI security, resilient systems, and applied cybersecurity.",
    researchAreas: ["AI", "Cybersecurity", "Resilient systems"],
    targetPrograms: ["Computer Engineering"],
    outreachStatus: "External safer outreach",
    sourceLabel: "Vault advisor scan, 2026-05-25"
  },
  {
    id: "pierre-yves-lajoie",
    fullName: "Pierre-Yves Lajoie",
    institutionName: "Polytechnique Montréal",
    institutionAliases: polytechniqueAliases,
    department: "Robotics / Distributed Systems",
    priority: "B",
    priorityScore: 68,
    fitSummary: "Robotics, distributed systems, and computer systems software.",
    contactAngle: "Distributed systems software and robotics infrastructure.",
    researchAreas: ["Robotics", "Distributed systems", "Computer systems software"],
    targetPrograms: ["Computer Engineering"],
    outreachStatus: "External safer outreach",
    sourceLabel: "Vault advisor scan, 2026-05-25"
  },
  {
    id: "ian-arawjo",
    fullName: "Ian Arawjo",
    institutionName: "Université de Montréal",
    institutionAliases: udemAliases,
    department: "DIRO / Mila",
    priority: "Sensitive",
    priorityScore: 66,
    fitSummary: "Human-AI interaction, dynamic programming languages, AI-assisted programming, and evaluation.",
    contactAngle: "AI-assisted programming and human-AI evaluation, but handle relationship context carefully.",
    researchAreas: ["Human-AI interaction", "Programming languages", "AI-assisted programming", "Evaluation"],
    targetPrograms: ["DIRO", "Computer Science", "Mila-affiliated research"],
    politicalSensitivity: "High",
    outreachStatus: "Sensitive DIRO/UdeM list",
    sourceLabel: "Vault advisor scan, 2026-05-25"
  },
  {
    id: "eugene-syriani",
    fullName: "Eugene Syriani",
    institutionName: "Université de Montréal",
    institutionAliases: udemAliases,
    department: "DIRO / GEODES",
    priority: "Sensitive",
    priorityScore: 65,
    fitSummary: "Model-driven engineering, code generation, agentic digital twins, and LLM prompt optimization.",
    contactAngle: "Model-driven engineering and code generation fit.",
    researchAreas: ["Model-driven engineering", "Code generation", "Agentic digital twins", "Prompt optimization"],
    targetPrograms: ["DIRO", "Computer Science"],
    politicalSensitivity: "Medium",
    outreachStatus: "Sensitive DIRO/UdeM list",
    sourceLabel: "Vault advisor scan, 2026-05-25"
  },
  {
    id: "michalis-famelis",
    fullName: "Michalis Famelis",
    institutionName: "Université de Montréal",
    institutionAliases: udemAliases,
    department: "DIRO / GEODES",
    priority: "Sensitive",
    priorityScore: 63,
    fitSummary: "Software engineering under uncertainty.",
    contactAngle: "Uncertainty-aware software engineering and model-based SE.",
    researchAreas: ["Software engineering", "Uncertainty", "Model-based engineering"],
    targetPrograms: ["DIRO", "Computer Science"],
    politicalSensitivity: "Medium",
    outreachStatus: "Sensitive DIRO/UdeM list",
    sourceLabel: "Vault advisor scan, 2026-05-25"
  },
  {
    id: "houari-sahraoui",
    fullName: "Houari Sahraoui",
    institutionName: "Université de Montréal",
    institutionAliases: udemAliases,
    department: "DIRO",
    priority: "Sensitive",
    priorityScore: 62,
    fitSummary: "Software engineering and AI for software engineering.",
    contactAngle: "AI for SE, software maintenance, and research fit framing.",
    researchAreas: ["Software engineering", "AI for SE", "Software maintenance"],
    targetPrograms: ["DIRO", "Computer Science"],
    politicalSensitivity: "Medium",
    outreachStatus: "Sensitive DIRO/UdeM list",
    sourceLabel: "Vault advisor scan, 2026-05-25"
  },
  {
    id: "uc-davis-muhao-chen",
    fullName: "Muhao Chen",
    institutionName: "University of California, Davis",
    institutionAliases: ucDavisAliases,
    department: "Computer Science",
    priority: "A+",
    priorityScore: 91,
    fitSummary: "Official CS AI/ML faculty signal; strong fit for AI, machine learning, and language/knowledge-oriented systems.",
    contactAngle: "Frame around AI systems evaluation, knowledge-intensive software tools, or LLM-assisted engineering.",
    researchAreas: ["Artificial intelligence", "Machine learning", "Computer science"],
    targetPrograms: ["Computer Science", "Computer Science Graduate Group", "AI/ML research"],
    outreachStatus: "Official UC Davis CS source",
    profileUrl: "https://cs.ucdavis.edu/directory",
    sourceLabel: "UC Davis CS directory and AI/ML faculty page"
  },
  {
    id: "uc-davis-ian-davidson",
    fullName: "Ian Davidson",
    institutionName: "University of California, Davis",
    institutionAliases: ucDavisAliases,
    department: "Computer Science",
    priority: "A",
    priorityScore: 88,
    fitSummary: "Listed in UC Davis CS AI/ML faculty; useful match for machine learning and applied AI directions.",
    contactAngle: "Ask about ML research fit and whether current projects connect to software/system behavior.",
    researchAreas: ["Machine learning", "Artificial intelligence", "Computer science"],
    targetPrograms: ["Computer Science", "AI/ML research"],
    outreachStatus: "Official UC Davis CS source",
    profileUrl: "https://cs.ucdavis.edu/directory",
    sourceLabel: "UC Davis CS directory and AI/ML faculty page"
  },
  {
    id: "uc-davis-lifu-huang",
    fullName: "Lifu Huang",
    institutionName: "University of California, Davis",
    institutionAliases: ucDavisAliases,
    department: "Computer Science",
    priority: "A",
    priorityScore: 86,
    fitSummary: "Assistant professor listed in UC Davis CS AI/ML faculty; promising for current AI/ML research fit.",
    contactAngle: "Position outreach around AI/ML research direction and possible graduate supervision fit.",
    researchAreas: ["Artificial intelligence", "Machine learning", "Computer science"],
    targetPrograms: ["Computer Science", "AI/ML research"],
    outreachStatus: "Official UC Davis CS source",
    profileUrl: "https://cs.ucdavis.edu/directory",
    sourceLabel: "UC Davis CS directory and AI/ML faculty page"
  },
  {
    id: "uc-davis-hamed-pirsiavash",
    fullName: "Hamed Pirsiavash",
    institutionName: "University of California, Davis",
    institutionAliases: ucDavisAliases,
    department: "Computer Science",
    priority: "A-",
    priorityScore: 84,
    fitSummary: "CS faculty member with AI/ML directory signal; relevant for applied AI and computer vision-adjacent interests.",
    contactAngle: "Use a concise AI/ML fit note and ask which current projects are open to graduate students.",
    researchAreas: ["Artificial intelligence", "Machine learning", "Computer science"],
    targetPrograms: ["Computer Science", "AI/ML research"],
    outreachStatus: "Official UC Davis CS source",
    profileUrl: "https://cs.ucdavis.edu/directory",
    sourceLabel: "UC Davis CS directory and AI/ML faculty page"
  },
  {
    id: "uc-davis-vladimir-filkov",
    fullName: "Vladimir Filkov",
    institutionName: "University of California, Davis",
    institutionAliases: ucDavisAliases,
    department: "Computer Science",
    priority: "A-",
    priorityScore: 82,
    fitSummary: "Appears in UC Davis CS AI/ML and software research groupings; good bridge between AI and software engineering.",
    contactAngle: "Frame around AI-assisted software engineering, empirical software behavior, or software analytics.",
    researchAreas: ["Software", "Artificial intelligence", "Machine learning", "Computer science"],
    targetPrograms: ["Computer Science", "Software research", "AI/ML research"],
    outreachStatus: "Official UC Davis CS source",
    profileUrl: "https://cs.ucdavis.edu/directory",
    sourceLabel: "UC Davis CS directory, AI/ML page, and software page"
  },
  {
    id: "uc-davis-cindy-rubio-gonzalez",
    fullName: "Cindy Rubio González",
    institutionName: "University of California, Davis",
    institutionAliases: ucDavisAliases,
    department: "Computer Science",
    priority: "B+",
    priorityScore: 78,
    fitSummary: "UC Davis CS software faculty signal; relevant for programming tools, software correctness, and developer-facing systems.",
    contactAngle: "Use a software correctness/tools angle, especially if connecting runtime behavior to engineering decisions.",
    researchAreas: ["Software", "Programming tools", "Computer science"],
    targetPrograms: ["Computer Science", "Software research"],
    outreachStatus: "Official UC Davis CS source",
    profileUrl: "https://cs.ucdavis.edu/directory",
    sourceLabel: "UC Davis CS directory and software page"
  },
  {
    id: "uc-davis-aditya-thakur",
    fullName: "Aditya Thakur",
    institutionName: "University of California, Davis",
    institutionAliases: ucDavisAliases,
    department: "Computer Science",
    priority: "B+",
    priorityScore: 76,
    fitSummary: "UC Davis CS software faculty signal; possible fit for program analysis and software engineering foundations.",
    contactAngle: "Frame around program analysis, software verification, or tool-assisted software understanding.",
    researchAreas: ["Software", "Program analysis", "Computer science"],
    targetPrograms: ["Computer Science", "Software research"],
    outreachStatus: "Official UC Davis CS source",
    profileUrl: "https://cs.ucdavis.edu/directory",
    sourceLabel: "UC Davis CS directory and software page"
  },
  {
    id: "uc-davis-hao-chen",
    fullName: "Hao Chen",
    institutionName: "University of California, Davis",
    institutionAliases: ucDavisAliases,
    department: "Computer Science",
    priority: "B+",
    priorityScore: 74,
    fitSummary: "UC Davis CS software/systems faculty signal; relevant for software and systems security-oriented interests.",
    contactAngle: "Use a systems/software angle and keep the first message narrowly tied to current lab work.",
    researchAreas: ["Software", "Systems", "Security", "Computer science"],
    targetPrograms: ["Computer Science", "Software research", "Systems research"],
    outreachStatus: "Official UC Davis CS source",
    profileUrl: "https://cs.ucdavis.edu/directory",
    sourceLabel: "UC Davis CS directory and software page"
  },
  {
    id: "uc-davis-soheil-ghiasi",
    fullName: "Soheil Ghiasi",
    institutionName: "University of California, Davis",
    institutionAliases: ucDavisAliases,
    department: "Electrical and Computer Engineering / Computer Science",
    priority: "B",
    priorityScore: 71,
    fitSummary: "ECE directory lists Computer Science affiliation; useful bridge for computer engineering and systems angles.",
    contactAngle: "Use computer engineering or systems implementation angle rather than pure CS theory.",
    researchAreas: ["Computer engineering", "Systems", "Electrical and computer engineering"],
    targetPrograms: ["Electrical and Computer Engineering", "Computer Engineering", "Computer Science"],
    outreachStatus: "Official UC Davis ECE source",
    profileUrl: "https://ece.ucdavis.edu/directory",
    sourceLabel: "UC Davis ECE directory"
  },
  {
    id: "uc-davis-junshan-zhang",
    fullName: "Junshan Zhang",
    institutionName: "University of California, Davis",
    institutionAliases: ucDavisAliases,
    department: "Electrical and Computer Engineering",
    priority: "B",
    priorityScore: 70,
    fitSummary: "ECE directory links Davis AI, Robotics, and Edge Research; useful for AI systems, robotics, and edge computing interests.",
    contactAngle: "Frame around AI systems, edge intelligence, or robotics infrastructure.",
    researchAreas: ["Artificial intelligence", "Robotics", "Edge research", "Electrical and computer engineering"],
    targetPrograms: ["Electrical and Computer Engineering", "Computer Engineering", "AI systems research"],
    outreachStatus: "Official UC Davis ECE source",
    profileUrl: "https://ece.ucdavis.edu/directory",
    sourceLabel: "UC Davis ECE directory"
  },
  {
    id: "mcmaster-hassan-ashtiani",
    fullName: "Dr. Hassan Ashtiani",
    institutionName: "McMaster University",
    institutionAliases: mcmasterAliases,
    department: "Computing and Software",
    priority: "A+",
    priorityScore: 90,
    fitSummary: "Computing & Software faculty; strong first-pass match for machine learning and theory-adjacent AI interests.",
    contactAngle: "Frame around ML foundations, reliable AI evaluation, or theory-informed software intelligence.",
    researchAreas: ["Machine learning", "Artificial intelligence", "Theory of computation", "Computer science"],
    targetPrograms: ["Computing and Software", "Computer Science", "Software Engineering"],
    outreachStatus: "Official McMaster Engineering source",
    profileUrl: "https://www.eng.mcmaster.ca/cas/faculty/dr-hassan-ashtiani/",
    sourceLabel: "McMaster Engineering faculty directory"
  },
  {
    id: "mcmaster-lingyang-chu",
    fullName: "Dr. Lingyang Chu",
    institutionName: "McMaster University",
    institutionAliases: mcmasterAliases,
    department: "Computing and Software",
    priority: "A",
    priorityScore: 87,
    fitSummary: "Computing & Software faculty; useful signal for AI, machine learning, and data-centric computing.",
    contactAngle: "Ask about current ML/data projects and whether software-system behavior is a possible application area.",
    researchAreas: ["Machine learning", "Data-centric computing", "Applied computing", "Computer science"],
    targetPrograms: ["Computing and Software", "Computer Science"],
    outreachStatus: "Official McMaster Engineering source",
    profileUrl: "https://www.eng.mcmaster.ca/cas/faculty/dr-lingyang-chu/",
    sourceLabel: "McMaster Engineering faculty directory"
  },
  {
    id: "mcmaster-richard-paige",
    fullName: "Dr. Richard Paige",
    institutionName: "McMaster University",
    institutionAliases: mcmasterAliases,
    department: "Computing and Software",
    priority: "A",
    priorityScore: 85,
    fitSummary: "Chair of Computing & Software; strong department-level signal for software engineering and model-driven systems.",
    contactAngle: "Use a software engineering / model-based systems angle, especially for decision-support tooling.",
    researchAreas: ["Software engineering", "Model-driven engineering", "Computing systems"],
    targetPrograms: ["Software Engineering", "Computing and Software", "Computer Science"],
    outreachStatus: "Official McMaster Engineering source",
    profileUrl: "https://www.eng.mcmaster.ca/cas/faculty/dr-richard-paige/",
    sourceLabel: "McMaster Engineering faculty directory"
  },
  {
    id: "mcmaster-fei-chiang",
    fullName: "Dr. Fei Chiang",
    institutionName: "McMaster University",
    institutionAliases: mcmasterAliases,
    department: "Computing and Software",
    priority: "A-",
    priorityScore: 82,
    fitSummary: "Computing & Software research leadership signal; relevant for information systems and data quality directions.",
    contactAngle: "Frame around data quality, interpretable decision data, or application intelligence for admissions/product systems.",
    researchAreas: ["Information systems", "Data management", "Data quality", "Computer science"],
    targetPrograms: ["Computing and Software", "Computer Science"],
    outreachStatus: "Official McMaster Engineering source",
    profileUrl: "https://www.eng.mcmaster.ca/cas/faculty/dr-fei-chiang/",
    sourceLabel: "McMaster Engineering faculty directory"
  },
  {
    id: "mcmaster-mark-lawford",
    fullName: "Dr. Mark Lawford",
    institutionName: "McMaster University",
    institutionAliases: mcmasterAliases,
    department: "Computing and Software",
    priority: "A-",
    priorityScore: 80,
    fitSummary: "Computing & Software graduate advisor; strong software engineering/formal methods department signal.",
    contactAngle: "Use software correctness, requirements, or safety-critical systems as the opening angle.",
    researchAreas: ["Software engineering", "Formal methods", "Software correctness"],
    targetPrograms: ["Software Engineering", "Computing and Software"],
    outreachStatus: "Official McMaster Engineering source",
    profileUrl: "https://www.eng.mcmaster.ca/cas/faculty/dr-mark-lawford/",
    sourceLabel: "McMaster Engineering faculty directory"
  },
  {
    id: "mcmaster-spencer-smith",
    fullName: "Dr. Spencer Smith",
    institutionName: "McMaster University",
    institutionAliases: mcmasterAliases,
    department: "Computing and Software",
    priority: "B+",
    priorityScore: 78,
    fitSummary: "Software Engineering undergraduate advisor; relevant for software engineering and requirements/modeling interests.",
    contactAngle: "Frame around requirements, explainable engineering artifacts, or software decision support.",
    researchAreas: ["Software engineering", "Requirements", "Modeling"],
    targetPrograms: ["Software Engineering", "Computing and Software"],
    outreachStatus: "Official McMaster Engineering source",
    profileUrl: "https://www.eng.mcmaster.ca/cas/faculty/dr-spencer-smith/",
    sourceLabel: "McMaster Engineering faculty directory"
  },
  {
    id: "mcmaster-rong-zheng",
    fullName: "Dr. Rong Zheng",
    institutionName: "McMaster University",
    institutionAliases: mcmasterAliases,
    department: "Computing and Software",
    priority: "B+",
    priorityScore: 76,
    fitSummary: "Computing & Software professor; useful match for networked, distributed, and systems-oriented computing.",
    contactAngle: "Use a systems/networked computing angle rather than pure ML.",
    researchAreas: ["Networked systems", "Distributed computing", "Computer science"],
    targetPrograms: ["Computing and Software", "Computer Science"],
    outreachStatus: "Official McMaster Engineering source",
    profileUrl: "https://www.eng.mcmaster.ca/cas/faculty/dr-rong-zheng/",
    sourceLabel: "McMaster Engineering faculty directory"
  },
  {
    id: "mcmaster-matthew-giamou",
    fullName: "Dr. Matthew Giamou",
    institutionName: "McMaster University",
    institutionAliases: mcmasterAliases,
    department: "Computing and Software",
    priority: "B+",
    priorityScore: 74,
    fitSummary: "Computing & Software assistant professor; useful signal for applied computing and autonomous/robotic systems angles.",
    contactAngle: "Connect AI/software systems interests to robotics, perception, or autonomous systems if relevant.",
    researchAreas: ["Applied computing", "Robotics", "Systems", "Computer science"],
    targetPrograms: ["Computing and Software", "Computer Science"],
    outreachStatus: "Official McMaster Engineering source",
    profileUrl: "https://www.eng.mcmaster.ca/cas/faculty/matthew-giamou/",
    sourceLabel: "McMaster Engineering faculty directory"
  },
  {
    id: "mcmaster-ameer-abdelhadi",
    fullName: "Dr. Ameer Abdelhadi",
    institutionName: "McMaster University",
    institutionAliases: mcmasterAliases,
    department: "Electrical and Computer Engineering",
    priority: "B",
    priorityScore: 71,
    fitSummary: "ECE assistant professor; useful bridge for computer engineering, embedded systems, and hardware/software systems.",
    contactAngle: "Use a computer engineering systems implementation angle, not a pure CS theory angle.",
    researchAreas: ["Computer engineering", "Embedded systems", "Hardware/software systems"],
    targetPrograms: ["Electrical and Computer Engineering", "Computer Engineering"],
    outreachStatus: "Official McMaster Engineering source",
    profileUrl: "https://www.eng.mcmaster.ca/ece/faculty/dr-ameer-abdelhadi/",
    sourceLabel: "McMaster Engineering faculty directory"
  },
  {
    id: "mcmaster-nicola-nicolici",
    fullName: "Dr. Nicola Nicolici",
    institutionName: "McMaster University",
    institutionAliases: mcmasterAliases,
    department: "Electrical and Computer Engineering",
    priority: "B",
    priorityScore: 70,
    fitSummary: "ECE professor; relevant for computer engineering, verification, and hardware/software reliability angles.",
    contactAngle: "Frame around reliable computer systems or verification-oriented engineering.",
    researchAreas: ["Computer engineering", "Verification", "Hardware/software reliability"],
    targetPrograms: ["Electrical and Computer Engineering", "Computer Engineering"],
    outreachStatus: "Official McMaster Engineering source",
    profileUrl: "https://www.eng.mcmaster.ca/ece/faculty/dr-nicola-nicolici/",
    sourceLabel: "McMaster Engineering faculty directory"
  },
  {
    id: "usc-bistra-dilkina",
    fullName: "Bistra Dilkina",
    institutionName: "University of Southern California",
    institutionAliases: uscAliases,
    department: "Thomas Lord Department of Computer Science",
    priority: "A+",
    priorityScore: 92,
    fitSummary: "CS faculty with strong AI/optimization and decision-support fit; good match for interpretable recommendation and planning systems.",
    contactAngle: "Frame around AI for decision support, optimization, or structured recommendation workflows.",
    researchAreas: ["Artificial intelligence", "Optimization", "Decision support", "Computer science"],
    targetPrograms: ["Computer Science", "AI research", "Software and systems"],
    outreachStatus: "Official USC CS source",
    profileUrl: "https://www.cs.usc.edu/directory/faculty/profile/?lname=Dilkina&fname=Bistra",
    sourceLabel: "USC CS faculty directory"
  },
  {
    id: "usc-sean-ren",
    fullName: "Sean (Xiang) Ren",
    institutionName: "University of Southern California",
    institutionAliases: uscAliases,
    department: "Thomas Lord Department of Computer Science",
    priority: "A+",
    priorityScore: 91,
    fitSummary: "CS faculty signal for language AI; strong fit for LLM-driven explanation, extraction, and advisor/school matching.",
    contactAngle: "Use an NLP/LLM information extraction and decision-support angle.",
    researchAreas: ["Natural language processing", "Artificial intelligence", "LLMs", "Computer science"],
    targetPrograms: ["Computer Science", "AI research", "NLP"],
    outreachStatus: "Official USC CS source",
    profileUrl: "https://www.cs.usc.edu/directory/faculty/profile/?lname=Ren&fname=Xiang",
    sourceLabel: "USC CS faculty directory"
  },
  {
    id: "usc-nenad-medvidovic",
    fullName: "Nenad Medvidovic",
    institutionName: "University of Southern California",
    institutionAliases: uscAliases,
    department: "Thomas Lord Department of Computer Science",
    priority: "A",
    priorityScore: 88,
    fitSummary: "CS professor and department chair; strong software architecture and systems-oriented fit.",
    contactAngle: "Frame around software architecture, software behavior understanding, or engineering decision representations.",
    researchAreas: ["Software engineering", "Software architecture", "Systems", "Computer science"],
    targetPrograms: ["Computer Science", "Software engineering"],
    outreachStatus: "Official USC CS source",
    profileUrl: "https://www.cs.usc.edu/directory/faculty/profile/?lname=Medvidovic&fname=Nenad",
    sourceLabel: "USC CS faculty directory"
  },
  {
    id: "usc-william-halfond",
    fullName: "William G.J. Halfond",
    institutionName: "University of Southern California",
    institutionAliases: uscAliases,
    department: "Thomas Lord Department of Computer Science",
    priority: "A",
    priorityScore: 86,
    fitSummary: "CS professor; strong fit for software engineering, testing, and software behavior analysis.",
    contactAngle: "Connect runtime/software facts to developer-facing representations and testing decisions.",
    researchAreas: ["Software engineering", "Testing", "Software behavior", "Computer science"],
    targetPrograms: ["Computer Science", "Software engineering"],
    outreachStatus: "Official USC CS source",
    profileUrl: "https://www.cs.usc.edu/directory/faculty/profile/?lname=Halfond&fname=William",
    sourceLabel: "USC CS faculty directory"
  },
  {
    id: "usc-cyrus-shahabi",
    fullName: "Cyrus Shahabi",
    institutionName: "University of Southern California",
    institutionAliases: uscAliases,
    department: "Computer Science / Electrical and Computer Engineering",
    priority: "A",
    priorityScore: 84,
    fitSummary: "Joint CS/ECE faculty signal for data systems and spatial information; useful for map-based decision products.",
    contactAngle: "Frame around spatial data, searchable decision facts, and map-based recommendation systems.",
    researchAreas: ["Databases", "Spatial data", "Information systems", "Computer science"],
    targetPrograms: ["Computer Science", "Data systems", "ECE"],
    outreachStatus: "Official USC CS/ECE source",
    profileUrl: "https://www.cs.usc.edu/directory/faculty/profile/?lname=Shahabi&fname=Cyrus",
    sourceLabel: "USC CS and ECE faculty directories"
  },
  {
    id: "usc-gaurav-sukhatme",
    fullName: "Gaurav Sukhatme",
    institutionName: "University of Southern California",
    institutionAliases: uscAliases,
    department: "Computer Science / Electrical and Computer Engineering",
    priority: "A-",
    priorityScore: 82,
    fitSummary: "Joint CS/ECE professor; strong robotics and embodied AI signal.",
    contactAngle: "Use robotics/AI systems angle if positioning toward autonomous decision-making.",
    researchAreas: ["Robotics", "Artificial intelligence", "Systems", "Computer science"],
    targetPrograms: ["Computer Science", "Robotics", "ECE"],
    outreachStatus: "Official USC CS/ECE source",
    profileUrl: "https://www.cs.usc.edu/directory/faculty/profile/?lname=Sukhatme&fname=Gaurav",
    sourceLabel: "USC CS and ECE faculty directories"
  },
  {
    id: "usc-stefanos-nikolaidis",
    fullName: "Stefanos Nikolaidis",
    institutionName: "University of Southern California",
    institutionAliases: uscAliases,
    department: "Thomas Lord Department of Computer Science",
    priority: "A-",
    priorityScore: 81,
    fitSummary: "CS faculty signal for human-centered robotics and AI; relevant for interactive recommendation workflows.",
    contactAngle: "Frame around human-AI interaction, robotics, or adaptive decision-support systems.",
    researchAreas: ["Human-AI interaction", "Robotics", "Artificial intelligence"],
    targetPrograms: ["Computer Science", "AI research", "Robotics"],
    outreachStatus: "Official USC CS source",
    profileUrl: "https://www.cs.usc.edu/directory/faculty/profile/?lname=Nikolaidis&fname=Stefanos",
    sourceLabel: "USC CS faculty directory"
  },
  {
    id: "usc-emilio-ferrara",
    fullName: "Emilio Ferrara",
    institutionName: "University of Southern California",
    institutionAliases: uscAliases,
    department: "Thomas Lord Department of Computer Science",
    priority: "A-",
    priorityScore: 80,
    fitSummary: "CS and communication faculty; useful for AI/social computing and information integrity angles.",
    contactAngle: "Connect AI-generated information, trust, and decision-support quality.",
    researchAreas: ["Artificial intelligence", "Social computing", "Information integrity"],
    targetPrograms: ["Computer Science", "AI research", "Information systems"],
    outreachStatus: "Official USC CS source",
    profileUrl: "https://www.cs.usc.edu/directory/faculty/profile/?lname=Ferrara&fname=Emilio",
    sourceLabel: "USC CS faculty directory"
  },
  {
    id: "usc-maryam-shanechi",
    fullName: "Maryam Shanechi",
    institutionName: "University of Southern California",
    institutionAliases: uscAliases,
    department: "Electrical and Computer Engineering / Computer Science",
    priority: "B+",
    priorityScore: 78,
    fitSummary: "Joint ECE/CS faculty signal for AI, signal processing, and adaptive systems.",
    contactAngle: "Use AI systems/adaptive modeling angle if research interest leans toward signals or health applications.",
    researchAreas: ["Artificial intelligence", "Signal processing", "Adaptive systems", "ECE"],
    targetPrograms: ["Electrical and Computer Engineering", "Computer Science"],
    outreachStatus: "Official USC CS/ECE source",
    profileUrl: "https://minghsiehece.usc.edu/directory/faculty/profile/?lname=Shanechi&fname=Maryam",
    sourceLabel: "USC ECE and CS faculty directories"
  },
  {
    id: "usc-mahdi-soltanolkotabi",
    fullName: "Mahdi Soltanolkotabi",
    institutionName: "University of Southern California",
    institutionAliases: uscAliases,
    department: "Electrical and Computer Engineering / Computer Science",
    priority: "B+",
    priorityScore: 76,
    fitSummary: "Joint ECE/CS/ISE faculty signal; useful for machine learning, optimization, and AI foundations.",
    contactAngle: "Frame around ML foundations, optimization, or reliable AI systems.",
    researchAreas: ["Machine learning", "Optimization", "Electrical and computer engineering", "Computer science"],
    targetPrograms: ["Electrical and Computer Engineering", "Computer Science", "AI research"],
    outreachStatus: "Official USC CS/ECE source",
    profileUrl: "https://minghsiehece.usc.edu/directory/faculty/profile/?lname=Soltanolkotabi&fname=Mahdi",
    sourceLabel: "USC ECE and CS faculty directories"
  },
  {
    id: "ucla-aditya-grover",
    fullName: "Aditya Grover",
    institutionName: "University of California, Los Angeles",
    institutionAliases: uclaAliases,
    department: "Computer Science Department",
    priority: "A+",
    priorityScore: 93,
    fitSummary: "CS assistant professor signal for machine learning and AI systems; strong fit for decision-support and recommendation workflows.",
    contactAngle: "Frame around ML systems for interpretable decision support or personalized academic planning.",
    researchAreas: ["Machine learning", "Artificial intelligence", "Decision support", "Computer science"],
    targetPrograms: ["Computer Science", "AI research", "Software and systems"],
    outreachStatus: "Official UCLA CS source",
    profileUrl: "https://catalog.registrar.ucla.edu/browse/Departments/ComputerScience/Faculty-Roster",
    sourceLabel: "UCLA Computer Science faculty roster"
  },
  {
    id: "ucla-baharan-mirzasoleiman",
    fullName: "Baharan Mirzasoleiman",
    institutionName: "University of California, Los Angeles",
    institutionAliases: uclaAliases,
    department: "Computer Science Department",
    priority: "A+",
    priorityScore: 91,
    fitSummary: "CS assistant professor signal for machine learning; useful for data-efficient and trustworthy AI recommendation problems.",
    contactAngle: "Use a robust ML / useful abstraction angle for school or advisor matching.",
    researchAreas: ["Machine learning", "Trustworthy AI", "Data-efficient AI", "Computer science"],
    targetPrograms: ["Computer Science", "AI research"],
    outreachStatus: "Official UCLA CS source",
    profileUrl: "https://catalog.registrar.ucla.edu/browse/Departments/ComputerScience/Faculty-Roster",
    sourceLabel: "UCLA Computer Science faculty roster"
  },
  {
    id: "ucla-guy-van-den-broeck",
    fullName: "Guy Van den Broeck",
    institutionName: "University of California, Los Angeles",
    institutionAliases: uclaAliases,
    department: "Computer Science Department",
    priority: "A+",
    priorityScore: 90,
    fitSummary: "CS professor signal for AI reasoning and probabilistic representations; strong fit for explainable matching and decision logic.",
    contactAngle: "Frame around interpretable AI representations for human decision-making.",
    researchAreas: ["Artificial intelligence", "Probabilistic reasoning", "Knowledge representation", "Explainable AI"],
    targetPrograms: ["Computer Science", "AI research"],
    outreachStatus: "Official UCLA CS source",
    profileUrl: "https://catalog.registrar.ucla.edu/browse/Departments/ComputerScience/Faculty-Roster",
    sourceLabel: "UCLA Computer Science faculty roster"
  },
  {
    id: "ucla-miryung-kim",
    fullName: "Miryung Kim",
    institutionName: "University of California, Los Angeles",
    institutionAliases: uclaAliases,
    department: "Computer Science Department",
    priority: "A",
    priorityScore: 88,
    fitSummary: "CS professor signal for software engineering; strong overlap with transforming raw software facts into useful developer-facing representations.",
    contactAngle: "Connect runtime/software behavior facts to actionable engineering abstractions.",
    researchAreas: ["Software engineering", "Program analysis", "Developer tools", "Software behavior"],
    targetPrograms: ["Computer Science", "Software engineering"],
    outreachStatus: "Official UCLA CS source",
    profileUrl: "https://catalog.registrar.ucla.edu/browse/Departments/ComputerScience/Faculty-Roster",
    sourceLabel: "UCLA Computer Science faculty roster"
  },
  {
    id: "ucla-jens-palsberg",
    fullName: "Jens Palsberg",
    institutionName: "University of California, Los Angeles",
    institutionAliases: uclaAliases,
    department: "Computer Science Department",
    priority: "A",
    priorityScore: 86,
    fitSummary: "CS professor signal for programming languages and software systems; useful if positioning toward static/runtime program understanding.",
    contactAngle: "Use a programming languages, program analysis, or reliable software systems angle.",
    researchAreas: ["Programming languages", "Program analysis", "Software systems", "Computer science"],
    targetPrograms: ["Computer Science", "Software engineering"],
    outreachStatus: "Official UCLA CS source",
    profileUrl: "https://catalog.registrar.ucla.edu/browse/Departments/ComputerScience/Faculty-Roster",
    sourceLabel: "UCLA Computer Science faculty roster"
  },
  {
    id: "ucla-yizhou-sun",
    fullName: "Yizhou Sun",
    institutionName: "University of California, Los Angeles",
    institutionAliases: uclaAliases,
    department: "Computer Science Department",
    priority: "A",
    priorityScore: 85,
    fitSummary: "CS professor signal for data mining and graph/ML methods; relevant to school/advisor recommendation and comparison graphs.",
    contactAngle: "Frame around graph-based recommendation, information extraction, or data-driven decision support.",
    researchAreas: ["Data mining", "Machine learning", "Graphs", "Recommendation"],
    targetPrograms: ["Computer Science", "AI research", "Data systems"],
    outreachStatus: "Official UCLA CS source",
    profileUrl: "https://catalog.registrar.ucla.edu/browse/Departments/ComputerScience/Faculty-Roster",
    sourceLabel: "UCLA Computer Science faculty roster"
  },
  {
    id: "ucla-xiang-anthony-chen",
    fullName: "Xiang Anthony Chen",
    institutionName: "University of California, Los Angeles",
    institutionAliases: uclaAliases,
    department: "Computer Science / Electrical and Computer Engineering",
    priority: "A-",
    priorityScore: 82,
    fitSummary: "Joint CS/ECE associate professor signal for human-computer interaction; useful for interactive comparison and decision workflows.",
    contactAngle: "Lead with human-centered AI tools that make complex application choices easier to inspect and act on.",
    researchAreas: ["Human-computer interaction", "Human-AI interaction", "Interactive systems"],
    targetPrograms: ["Computer Science", "Electrical and Computer Engineering", "HCI"],
    outreachStatus: "Official UCLA CS/ECE source",
    profileUrl: "https://www.ee.ucla.edu/albertl-faculty/",
    sourceLabel: "UCLA CS roster and ECE faculty directory"
  },
  {
    id: "ucla-stefano-soatto",
    fullName: "Stefano Soatto",
    institutionName: "University of California, Los Angeles",
    institutionAliases: uclaAliases,
    department: "Computer Science / Electrical and Computer Engineering",
    priority: "A-",
    priorityScore: 81,
    fitSummary: "Joint CS/ECE professor signal for AI, vision, and systems; relevant for representation learning and decision-support infrastructure.",
    contactAngle: "Use a representation-learning or AI systems angle, not a pure admissions-product pitch.",
    researchAreas: ["Artificial intelligence", "Computer vision", "Representation learning", "Systems"],
    targetPrograms: ["Computer Science", "Electrical and Computer Engineering", "AI research"],
    outreachStatus: "Official UCLA CS/ECE source",
    profileUrl: "https://www.ee.ucla.edu/albertl-faculty/",
    sourceLabel: "UCLA CS roster and ECE faculty directory"
  },
  {
    id: "ucla-lin-f-yang",
    fullName: "Lin F. Yang",
    institutionName: "University of California, Los Angeles",
    institutionAliases: uclaAliases,
    department: "Electrical and Computer Engineering Department",
    priority: "B+",
    priorityScore: 78,
    fitSummary: "ECE associate professor signal for machine learning, reinforcement learning, optimization, and control.",
    contactAngle: "Frame around optimization and ML methods for adaptive decision support.",
    researchAreas: ["Machine learning", "Reinforcement learning", "Optimization", "Control"],
    targetPrograms: ["Electrical and Computer Engineering", "AI research"],
    outreachStatus: "Official UCLA ECE source",
    profileUrl: "https://www.ee.ucla.edu/albertl-faculty/",
    sourceLabel: "UCLA ECE faculty directory"
  },
  {
    id: "ucla-nader-sehatbakhsh",
    fullName: "Nader Sehatbakhsh",
    institutionName: "University of California, Los Angeles",
    institutionAliases: uclaAliases,
    department: "Electrical and Computer Engineering Department",
    priority: "B+",
    priorityScore: 76,
    fitSummary: "ECE assistant professor signal for computer engineering and secure/reliable systems; useful if research direction leans systems/security.",
    contactAngle: "Use a secure systems, computer engineering, or reliable infrastructure angle.",
    researchAreas: ["Computer engineering", "Systems security", "Reliable systems", "ECE"],
    targetPrograms: ["Electrical and Computer Engineering", "Computer Engineering"],
    outreachStatus: "Official UCLA ECE source",
    profileUrl: "https://www.ee.ucla.edu/albertl-faculty/",
    sourceLabel: "UCLA ECE faculty directory"
  }
];
