import type { AdvisorCard } from "./types";

const polytechniqueAliases = [
  "Polytechnique Montréal",
  "Polytechnique Montreal",
  "École Polytechnique de Montréal",
  "Ecole Polytechnique de Montreal",
  "Polytechnic School of Montreal"
];

const udemAliases = [
  "Université de Montréal",
  "University of Montreal",
  "University of Montréal",
  "UdeM",
  "Montreal University"
];

export const localAdvisorCards: AdvisorCard[] = [
  {
    id: "foutse-khomh",
    fullName: "Foutse Khomh",
    institutionName: "Polytechnique Montréal",
    institutionAliases: polytechniqueAliases,
    department: "Software Engineering / Mila",
    priority: "S",
    priorityScore: 98,
    fitSummary: "Software quality, ML/AI systems reliability, LLM code generation benchmarks, and multi-agent evaluation.",
    contactAngle: "LLM code generation QA/testing, robustness of AI software systems.",
    researchAreas: ["Software quality", "AI reliability", "LLM code generation", "Multi-agent evaluation"],
    targetPrograms: ["Software Engineering", "Computer Engineering", "Mila-affiliated research"],
    outreachStatus: "External safer outreach",
    sourceLabel: "Vault advisor scan, 2026-05-25"
  },
  {
    id: "heng-li",
    fullName: "Heng Li",
    institutionName: "Polytechnique Montréal",
    institutionAliases: polytechniqueAliases,
    department: "Software / Systems",
    priority: "S-",
    priorityScore: 94,
    fitSummary: "Software systems performance, reliability, runtime monitoring, and infrastructure quality.",
    contactAngle: "AI software reliability, runtime monitoring, infra quality.",
    researchAreas: ["Software systems", "Performance", "Reliability", "Runtime monitoring"],
    targetPrograms: ["Software Engineering", "Computer Engineering"],
    outreachStatus: "External safer outreach",
    sourceLabel: "Vault advisor scan, 2026-05-25"
  },
  {
    id: "maxime-lamothe",
    fullName: "Maxime Lamothe",
    institutionName: "Polytechnique Montréal",
    institutionAliases: polytechniqueAliases,
    department: "Software Engineering",
    priority: "A+",
    priorityScore: 91,
    fitSummary: "Software engineering, logic programming, computer systems software, and LLM-assisted SE tools.",
    contactAngle: "LLM-assisted software engineering tools, program analysis, testing.",
    researchAreas: ["Software engineering", "Logic programming", "Program analysis", "Testing"],
    targetPrograms: ["Software Engineering"],
    outreachStatus: "External safer outreach",
    sourceLabel: "Vault advisor scan, 2026-05-25"
  },
  {
    id: "mohammad-hamdaqa",
    fullName: "Mohammad Hamdaqa",
    institutionName: "Polytechnique Montréal",
    institutionAliases: polytechniqueAliases,
    department: "Software Engineering",
    priority: "A+",
    priorityScore: 90,
    fitSummary: "Software development, software engineering, systems, and knowledge representation.",
    contactAngle: "Software systems and knowledge representation angle; recruiting signal found.",
    researchAreas: ["Software development", "Systems", "Knowledge representation"],
    targetPrograms: ["Software Engineering"],
    recruitingSignal: "Recruiting signal found",
    outreachStatus: "External safer outreach",
    sourceLabel: "Vault advisor scan, 2026-05-25"
  },
  {
    id: "bentley-oakes",
    fullName: "Bentley Oakes",
    institutionName: "Polytechnique Montréal",
    institutionAliases: polytechniqueAliases,
    department: "Software Engineering",
    priority: "A",
    priorityScore: 86,
    fitSummary: "Software engineering, AI, simulation, and knowledge representation.",
    contactAngle: "AI + simulation + software engineering; recruiting signal found.",
    researchAreas: ["Software engineering", "AI", "Simulation", "Knowledge representation"],
    targetPrograms: ["Software Engineering"],
    recruitingSignal: "Recruiting signal found",
    outreachStatus: "External safer outreach",
    sourceLabel: "Vault advisor scan, 2026-05-25"
  },
  {
    id: "zohreh-sharafi",
    fullName: "Zohreh Sharafi",
    institutionName: "Polytechnique Montréal",
    institutionAliases: polytechniqueAliases,
    department: "Software Engineering",
    priority: "A",
    priorityScore: 84,
    fitSummary: "Software engineering and human factors.",
    contactAngle: "Developer experience, human factors, and software engineering evaluation.",
    researchAreas: ["Software engineering", "Human factors", "Developer experience"],
    targetPrograms: ["Software Engineering"],
    outreachStatus: "External safer outreach",
    sourceLabel: "Vault advisor scan, 2026-05-25"
  },
  {
    id: "ettore-merlo",
    fullName: "Ettore Merlo",
    institutionName: "Polytechnique Montréal",
    institutionAliases: polytechniqueAliases,
    department: "Software / Cybersecurity",
    priority: "A-",
    priorityScore: 80,
    fitSummary: "Cybersecurity, AI, and software engineering.",
    contactAngle: "Security and AI-assisted software engineering overlap.",
    researchAreas: ["Cybersecurity", "AI", "Software engineering"],
    targetPrograms: ["Software Engineering", "Computer Engineering"],
    outreachStatus: "External safer outreach",
    sourceLabel: "Vault advisor scan, 2026-05-25"
  },
  {
    id: "jinghui-cheng",
    fullName: "Jinghui Cheng",
    institutionName: "Polytechnique Montréal",
    institutionAliases: polytechniqueAliases,
    department: "Software Engineering",
    priority: "A-",
    priorityScore: 79,
    fitSummary: "Software engineering, human factors, and information systems design.",
    contactAngle: "Human-centered software systems and information systems design.",
    researchAreas: ["Software engineering", "Human factors", "Information systems"],
    targetPrograms: ["Software Engineering"],
    outreachStatus: "External safer outreach",
    sourceLabel: "Vault advisor scan, 2026-05-25"
  },
  {
    id: "amal-zouaq",
    fullName: "Amal Zouaq",
    institutionName: "Polytechnique Montréal",
    institutionAliases: polytechniqueAliases,
    department: "AI / Knowledge Representation",
    priority: "A-",
    priorityScore: 78,
    fitSummary: "AI and knowledge representation.",
    contactAngle: "Knowledge representation for AI systems; recruiting signal found.",
    researchAreas: ["AI", "Knowledge representation", "Semantic systems"],
    targetPrograms: ["Computer Engineering", "AI-related research"],
    recruitingSignal: "Recruiting signal found",
    outreachStatus: "External safer outreach",
    sourceLabel: "Vault advisor scan, 2026-05-25"
  },
  {
    id: "omar-abdul-wahab",
    fullName: "Omar Abdul Wahab",
    institutionName: "Polytechnique Montréal",
    institutionAliases: polytechniqueAliases,
    department: "AI / Cybersecurity",
    priority: "B+",
    priorityScore: 73,
    fitSummary: "AI and cybersecurity overlap.",
    contactAngle: "AI security, resilient systems, and applied cybersecurity.",
    researchAreas: ["AI", "Cybersecurity", "Resilient systems"],
    targetPrograms: ["Computer Engineering"],
    outreachStatus: "External safer outreach",
    sourceLabel: "Vault advisor scan, 2026-05-25"
  },
  {
    id: "pierre-yves-lajoie",
    fullName: "Pierre-Yves Lajoie",
    institutionName: "Polytechnique Montréal",
    institutionAliases: polytechniqueAliases,
    department: "Robotics / Distributed Systems",
    priority: "B",
    priorityScore: 68,
    fitSummary: "Robotics, distributed systems, and computer systems software.",
    contactAngle: "Distributed systems software and robotics infrastructure.",
    researchAreas: ["Robotics", "Distributed systems", "Computer systems software"],
    targetPrograms: ["Computer Engineering"],
    outreachStatus: "External safer outreach",
    sourceLabel: "Vault advisor scan, 2026-05-25"
  },
  {
    id: "ian-arawjo",
    fullName: "Ian Arawjo",
    institutionName: "Université de Montréal",
    institutionAliases: udemAliases,
    department: "DIRO / Mila",
    priority: "Sensitive",
    priorityScore: 66,
    fitSummary: "Human-AI interaction, dynamic programming languages, AI-assisted programming, and evaluation.",
    contactAngle: "AI-assisted programming and human-AI evaluation, but handle relationship context carefully.",
    researchAreas: ["Human-AI interaction", "Programming languages", "AI-assisted programming", "Evaluation"],
    targetPrograms: ["DIRO", "Computer Science", "Mila-affiliated research"],
    politicalSensitivity: "High",
    outreachStatus: "Sensitive DIRO/UdeM list",
    sourceLabel: "Vault advisor scan, 2026-05-25"
  },
  {
    id: "eugene-syriani",
    fullName: "Eugene Syriani",
    institutionName: "Université de Montréal",
    institutionAliases: udemAliases,
    department: "DIRO / GEODES",
    priority: "Sensitive",
    priorityScore: 65,
    fitSummary: "Model-driven engineering, code generation, agentic digital twins, and LLM prompt optimization.",
    contactAngle: "Model-driven engineering and code generation fit.",
    researchAreas: ["Model-driven engineering", "Code generation", "Agentic digital twins", "Prompt optimization"],
    targetPrograms: ["DIRO", "Computer Science"],
    politicalSensitivity: "Medium",
    outreachStatus: "Sensitive DIRO/UdeM list",
    sourceLabel: "Vault advisor scan, 2026-05-25"
  },
  {
    id: "michalis-famelis",
    fullName: "Michalis Famelis",
    institutionName: "Université de Montréal",
    institutionAliases: udemAliases,
    department: "DIRO / GEODES",
    priority: "Sensitive",
    priorityScore: 63,
    fitSummary: "Software engineering under uncertainty.",
    contactAngle: "Uncertainty-aware software engineering and model-based SE.",
    researchAreas: ["Software engineering", "Uncertainty", "Model-based engineering"],
    targetPrograms: ["DIRO", "Computer Science"],
    politicalSensitivity: "Medium",
    outreachStatus: "Sensitive DIRO/UdeM list",
    sourceLabel: "Vault advisor scan, 2026-05-25"
  },
  {
    id: "houari-sahraoui",
    fullName: "Houari Sahraoui",
    institutionName: "Université de Montréal",
    institutionAliases: udemAliases,
    department: "DIRO",
    priority: "Sensitive",
    priorityScore: 62,
    fitSummary: "Software engineering and AI for software engineering.",
    contactAngle: "AI for SE, software maintenance, and research fit framing.",
    researchAreas: ["Software engineering", "AI for SE", "Software maintenance"],
    targetPrograms: ["DIRO", "Computer Science"],
    politicalSensitivity: "Medium",
    outreachStatus: "Sensitive DIRO/UdeM list",
    sourceLabel: "Vault advisor scan, 2026-05-25"
  }
];
